In [1]:
import pandas as pd
from keras.models import Sequential, model_from_json
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

Using TensorFlow backend.

In [2]:
df = pd.read_csv("raw_input.csv")
cols = [0,1]
df2 = df.drop(df.columns[cols],axis=1)
df2

,home,season_hits_for,season_hits_against,season_runs_for,season_runs_against,season_errors,season_wins,ml_odds,rl_odds
0,1,47,38,21,20,1,3,-151,127
1,0,41,35,18,18,8,2,134,-146
2,1,49,39,38,33,4,4,101,-191
3,0,43,45,37,33,3,2,-115,165
4,1,31,41,19,28,4,2,210,138
5,0,26,26,18,15,3,3,-244,-160
6,1,43,39,22,15,3,4,104,-201
7,0,42,39,36,20,0,4,-118,172
8,1,59,62,32,36,4,2,136,-143
9,0,57,54,25,32,3,3,-153,123
10,1,37,48,25,34,4,4,122,-128
11,0,42,41,26,28,5,2,-136,110
12,1,50,47,33,28,2,3,-144,138
13,0,44,52,37,26,7,4,128,-162
14,1,39,40,17,29,2,2,140,-116
15,0,56,40,31,14,2,4,-157,-102
16,1,49,46,28,29,2,2,-197,-110
17,0,53,55,28,46,5,2,174,-107
18,1,42,44,32,19,4,4,-173,-108
19,0,47,55,20,33,8,3,154,-110

In [3]:
def load_model():
    # loading model
    model = model_from_json(open('ML_model_architecture.json').read())
    model.load_weights('ML_model_weights.h5')
    model.compile(loss='categorical_crossentropy', optimizer='adam')
    return model

In [4]:
# load
model = load_model()

# predictions
predictions = model.predict_classes(df2, verbose=2)
print(predictions)

[1 0 0 0 0 1 0 0 0 1 0 1 1 0 0 1 1 0 1 0]

In [5]:
p = predictions.tolist()
df['ml_outcome'] = p
cols = [0,3,4,5,6,7,8]
df.drop(df.columns[cols],axis=1,inplace=True)
df

,Team,home,season_hits_for,season_hits_against,season_runs_for,season_runs_against,season_errors,season_wins,ml_odds,rl_odds,ml_outcome
0,TOR,1,47,38,21,20,1,3,-151,127,1
1,WSN,0,41,35,18,18,8,2,134,-146,0
2,CHC,1,49,39,38,33,4,4,101,-191,0
3,CIN,0,43,45,37,33,3,2,-115,165,0
4,BAL,1,31,41,19,28,4,2,210,138,0
5,NYY,0,26,26,18,15,3,3,-244,-160,1
6,CLE,1,43,39,22,15,3,4,104,-201,0
7,MIN,0,42,39,36,20,0,4,-118,172,0
8,BOS,1,59,62,32,36,4,2,136,-143,0
9,NYM,0,57,54,25,32,3,3,-153,123,1
10,DET,1,37,48,25,34,4,4,122,-128,0
11,KCR,0,42,41,26,28,5,2,-136,110,1
12,ATL,1,50,47,33,28,2,3,-144,138,1
13,TBR,0,44,52,37,26,7,4,128,-162,0
14,ARI,1,39,40,17,29,2,2,140,-116,0
15,LAD,0,56,40,31,14,2,4,-157,-102,1
16,LAA,1,49,46,28,29,2,2,-197,-110,1
17,SEA,0,53,55,28,46,5,2,174,-107,0
18,SDP,1,42,44,32,19,4,4,-173,-108,1
19,SFG,0,47,55,20,33,8,3,154,-110,0

In [6]:
from joblib import dump, load
rf = load('ml_rf.joblib')

In [7]:
predictions = rf.predict(df2).tolist()
df['ml_outcome2'] = predictions
df

,Team,home,season_hits_for,season_hits_against,season_runs_for,season_runs_against,season_errors,season_wins,ml_odds,rl_odds,ml_outcome,ml_outcome2
0,TOR,1,47,38,21,20,1,3,-151,127,1,0
1,WSN,0,41,35,18,18,8,2,134,-146,0,0
2,CHC,1,49,39,38,33,4,4,101,-191,0,1
3,CIN,0,43,45,37,33,3,2,-115,165,0,0
4,BAL,1,31,41,19,28,4,2,210,138,0,0
5,NYY,0,26,26,18,15,3,3,-244,-160,1,1
6,CLE,1,43,39,22,15,3,4,104,-201,0,1
7,MIN,0,42,39,36,20,0,4,-118,172,0,1
8,BOS,1,59,62,32,36,4,2,136,-143,0,0
9,NYM,0,57,54,25,32,3,3,-153,123,1,1
10,DET,1,37,48,25,34,4,4,122,-128,0,0
11,KCR,0,42,41,26,28,5,2,-136,110,1,1
12,ATL,1,50,47,33,28,2,3,-144,138,1,0
13,TBR,0,44,52,37,26,7,4,128,-162,0,0
14,ARI,1,39,40,17,29,2,2,140,-116,0,1
15,LAD,0,56,40,31,14,2,4,-157,-102,1,1
16,LAA,1,49,46,28,29,2,2,-197,-110,1,1
17,SEA,0,53,55,28,46,5,2,174,-107,0,0
18,SDP,1,42,44,32,19,4,4,-173,-108,1,1
19,SFG,0,47,55,20,33,8,3,154,-110,0,0

In [8]:
df.to_csv('ml_predictions.csv')